-- MySQL Script generated by MySQL Workbench
-- Thu Jul 11 20:07:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema topc_iems
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `topc_iems` ;

-- -----------------------------------------------------
-- Schema topc_iems
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `topc_iems` DEFAULT CHARACTER SET utf8 ;
USE `topc_iems` ;

-- -----------------------------------------------------
-- Table `topc_iems`.`t_iems_auth_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topc_iems`.`t_iems_auth_role` ;

CREATE TABLE IF NOT EXISTS `topc_iems`.`t_iems_auth_role` (
  `pk_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `role_id` VARCHAR(32) NOT NULL COMMENT '角色id',
  `role_name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT '角色名称',
  `remark` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '角色描述',
  `create_by` VARCHAR(50) NULL COMMENT '创建人',
  `create_date` DATETIME  COMMENT '创建时间',
  `update_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME  COMMENT '更新时间',
  `is_deleted` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否删除 Y/N',
  PRIMARY KEY (`pk_id`));


-- -----------------------------------------------------
-- Table `topc_iems`.`t_iems_auth_role_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topc_iems`.`t_iems_auth_role_menu` ;

CREATE TABLE IF NOT EXISTS `topc_iems`.`t_iems_auth_role_menu` (
  `pk_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `role_id` VARCHAR(32) NOT NULL COMMENT '角色id',
  `menu_id` VARCHAR(32) NOT NULL COMMENT '菜单/按钮id',
  `create_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME  COMMENT '创建时间',
  `update_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME  COMMENT '更新时间',
  `is_deleted` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否删除 Y/N',
  PRIMARY KEY (`pk_id`));


-- -----------------------------------------------------
-- Table `topc_iems`.`t_iems_auth_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topc_iems`.`t_iems_auth_menu` ;

CREATE TABLE IF NOT EXISTS `topc_iems`.`t_iems_auth_menu` (
  `pk_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `menu_id` VARCHAR(32) NOT NULL COMMENT '菜单/按钮id',
  `menu_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '菜单/按钮名称',
  `parent_id` VARCHAR(32) NOT NULL COMMENT '上级菜单id',
  `url` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '菜单url',
  `perms` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '菜单url',
  `icon` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '图标',
  `type` CHAR(2) CHARACTER SET 'utf8' NOT NULL COMMENT '类型 0菜单 1按钮',
  `order_num` BIGINT(20) NULL DEFAULT NULL COMMENT '排序',
  `create_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME  COMMENT '创建时间',
  `update_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME  COMMENT '更新时间',
  `is_deleted` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否删除 Y/N',
  PRIMARY KEY (`pk_id`));


-- -----------------------------------------------------
-- Table `topc_iems`.`t_iems_auth_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topc_iems`.`t_iems_auth_user_role` ;

CREATE TABLE IF NOT EXISTS `topc_iems`.`t_iems_auth_user_role` (
  `pk_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `user_id` VARCHAR(32) NOT NULL COMMENT '用户id',
  `role_id` VARCHAR(32) NOT NULL COMMENT '角色id',
  `create_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME  COMMENT '创建时间',
  `update_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME  COMMENT '更新时间',
  `is_deleted` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否删除 Y/N',
  PRIMARY KEY (`pk_id`));


-- -----------------------------------------------------
-- Table `topc_iems`.`t_iems_auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topc_iems`.`t_iems_auth_user` ;

CREATE TABLE IF NOT EXISTS `topc_iems`.`t_iems_auth_user` (
  `pk_id` VARCHAR(64) NOT NULL COMMENT '主键ID',
  `user_id` VARCHAR(32) NOT NULL COMMENT '用户id',
  `user_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '用户名',
  `password` VARCHAR(128) CHARACTER SET 'utf8' NOT NULL COMMENT '密码',
  `create_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
  `create_date` DATETIME  COMMENT '创建时间',
  `update_by` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
  `update_date` DATETIME  COMMENT '更新时间',
  `is_deleted` VARCHAR(1) NULL DEFAULT NULL COMMENT '是否删除 Y/N',
  PRIMARY KEY (`pk_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
